=== KhaosResearch/enbic2lab-images/annotation.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://enbic2lab.uma.es/components.schema.json",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "description": "Specifies the category of the component within the data workflow.",
      "enum": [
        "DataProcessing",
        "DataAnalysing",
        "DataSink",
        "DataCollection",
        "DataFlow"
      ]
    },
    "name": {
      "type": "string",
      "description": "Name of the component with no spaces or special characters."
    },
    "label": {
      "type": "string",
      "description": "A concise, descriptive name for the component that will be displayed in user interfaces."
    },
    "description": {
      "type": "string",
      "description": "A detailed description of the component's purpose and functionality."
    },
    "license": {
      "type": "string",
      "description": "Software license governing the component's use and distribution."
    },
    "version": {
      "type": "string",
      "description": "The release version of the component, following semantic versioning when applicable.",
      "default": "0.0.1"
    },
    "dockerImage": {
      "type": "string",
      "description": "The full identifier for the Docker image used to execute the component, including the repository and tag.",
      "default": "docker.io/docker/hello-world:latest"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "An array of keywords to facilitate search and categorization of the component.",
      "uniqueItems": true
    },
    "parameters": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The unique name used internally by the component to identify the parameter."
          },
          "label": {
            "type": "string",
            "description": "A readable name for the parameter used in user interfaces."
          },
          "description": {
            "type": "string",
            "description": "Explains what the parameter does and how it affects the component's behavior."
          },
          "type": {
            "type": "string",
            "description": "Specifies the expected data type for the parameter value.",
            "enum": [
              "string",
              "number",
              "integer",
              "float",
              "boolean"
            ]
          },
          "defaultValue": {
            "type": [
              "number",
              "string",
              "null"
            ],
            "description": "Provides a default value for the parameter, to be used when no value is explicitly provided.",
            "properties": {}
          },
          "readOnly": {
            "type": "boolean",
            "default": false,
            "description": "Indicates whether this parameter should not be modified by the user. If set to 'true', the parameter is considered read-only and cannot be altered by the user."
          }
        },
        "required": [
          "type",
          "name",
          "label",
          "description"
        ],
        "description": "Parameters that can be configured for the component."
      },
      "uniqueItems": true
    },
    "inputs": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The unique name identifying each input required by the component."
          },
          "label": {
            "type": "string",
            "description": "A label providing a human-readable name for the input."
          },
          "path": {
            "type": "string",
            "description": "The location or source path where the input data can be found."
          },
          "type": {
            "type": "string",
            "description": "The data type of the input.",
            "enum": [
              "bin",
              "fastq",
              "image",
              "map",
              "pdf",
              "rar",
              "sav",
              "shp",
              "tempfile",
              "text",
              "tabulardataset",
              "docx",
              "xlsx",
              "html",
              "json",
              "rdf",
              "xml",
              "tiff",
              "zip",
              "pkl",
              "onnx"
            ]
          }
        },
        "required": [
          "name",
          "label",
          "path",
          "type"
        ],
        "description": "Input data sources for the component."
      }
    },
    "outputs": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The unique name identifying each output generated by the component."
          },
          "label": {
            "type": "string",
            "description": "A label providing a human-readable name for the output."
          },
          "path": {
            "type": "string",
            "description": "The destination path where output data will be written."
          },
          "type": {
            "type": "string",
            "description": "The data type of the output.",
            "enum": [
              "bin",
              "fastq",
              "image",
              "map",
              "pdf",
              "rar",
              "sav",
              "shp",
              "tempfile",
              "text",
              "tabulardataset",
              "docx",
              "xlsx",
              "html",
              "json",
              "rdf",
              "xml",
              "tiff",
              "zip",
              "pkl",
              "onnx"
            ]
          }
        },
        "required": [
          "name",
          "label",
          "path",
          "type"
        ],
        "description": "Output data destinations for the component."
      }
    },
    "mainScriptPath": {
      "type": "string",
      "description": "The filesystem path to the executable script."
    },
    "testPath": {
      "type": "string",
      "description": "The filesystem path to the component's test script or suite."
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of an external library or service that this component relies on-"
          },
          "version": {
            "type": "string",
            "description": "The specified version of the dependency that is known to be compatible with this component."
          },
          "license": {
            "type": "string",
            "description": "The license governing the dependency, which may impact the overall licensing of the component."
          },
          "url": {
            "type": "string",
            "description": "A URL or other locator where the dependency can be accessed or reviewed."
          }
        },
        "required": [
          "name",
          "version",
          "license"
        ],
        "description": "Dependencies required to run the component."
      }
    },
    "resources": {
      "type": "object",
      "properties": {
        "cores": {
          "type": "integer",
          "description": "The number of CPU cores requested for processing."
        },
        "memory": {
          "type": "integer",
          "description": "The quantity of RAM required for the component, specified in Megabytes (MB)."
        },
        "gpuNeeded": {
          "type": "boolean",
          "description": "Flag to indicate whether the component requires GPU support.",
          "default": false
        },
        "gpuMemory": {
          "type": [
            "integer",
            "null"
          ],
          "description": "The amount of GPU memory required, specified in Megabytes (MB), applicable if `gpuNeeded` is true."
        },
        "estimatedTimeInMin": {
          "type": "integer",
          "description": "An approximate time in minutes that the component will take to execute."
        }
      },
      "required": [
        "cores",
        "memory",
        "gpuNeeded",
        "gpuMemory",
        "estimatedTimeInMin"
      ],
      "description": "Resource requirements for running the component."
    },
    "publicationDate": {
      "type": "string",
      "format": "date-time",
      "description": "The date and time when the component was officially made available."
    },
    "author": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "description": "Author email."
        },
        "affiliation": {
          "type": "string",
          "description": "The institution or organization with which the author is associated."
        }
      },
      "required": [
        "email",
        "affiliation"
      ],
      "description": "Identifies the individual or organization responsible for creating the component."
    },
    "contributor": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "format": "email",
            "default": "Contact email.",
            "description": "Contributor email."
          },
          "affiliation": {
            "type": "string",
            "description": "The institution or organization with which the contributor is associated."
          }
        },
        "required": [
          "email"
        ]
      },
      "description": "Contact information for the component's author or contributor."
    },
    "maintainer": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "format": "email",
            "default": "Contact email.",
            "description": "Maintainer email."
          },
          "affiliation": {
            "type": "string",
            "description": "The institution or organization with which the maintainer is associated."
          }
        },
        "required": [
          "email"
        ]
      },
      "description": "Contact information for the component's author or maintainers."
    }
  },
  "required": [
    "type",
    "name",
    "label",
    "description",
    "license",
    "version",
    "dockerImage",
    "outputs",
    "mainScriptPath",
    "dependencies",
    "resources",
    "publicationDate",
    "author"
  ]
}

=== KhaosResearch/enbic2lab-images/components/misc/LinePlot/annotation.json
{
    "type": "DataSink",
    "name": "GenericLinePlot",
    "label": "Line Plot",
    "description": "Generic simple Line chart plot",
    "license": "cc by-nc-nd 4.0",
    "version": "1.0.2",
    "dockerImage": "192.168.219.5:8098/enbic2lab/misc/generic_lineplot:1.0.2",
    "tags": ["enbic2lab-misc", "cc by-nc-nd 4.0", "by-nc-nd", "Sink", "generic"],
    "parameters": [
      {
        "name": "--filepath",
        "label": "Filepath",
        "description": "Path to the CSV file",
        "defaultValue": "{{.inputs.input.path}}",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "--x-column",
        "label": "Column for X axis",
        "description": "Column name for the X axis",
        "type": "string"
      },
      {
        "name": "--y-column",
        "label": "Column for Y axis",
        "description": "Column name for the Y axis",
        "type": "string"
      },
      {
        "name": "--hue",
        "label": "Hue",
        "description": "Column name for the hue",
        "defaultValue": null,
        "type": "string"
      },
      {
        "name": "--palette",
        "label": "Palette",
        "description": "Color palette",
        "defaultValue": null,
        "type": "string"
      },
      {
        "name": "--style",
        "label": "Style column",
        "description": "Style column for the plot",
        "defaultValue": null,
        "type": "string"
      },
      {
        "name": "--markers",
        "label": "Markers on style",
        "description": "Change markers for the style",
        "defaultValue": "False",
        "type": "string"
      },
      {
        "name": "--dashes",
        "label": "Dashes on style",
        "description": "Change dashes for the style",
        "defaultValue": "False",
        "type": "string"
      },
      {
        "name": "--grid",
        "label": "Show grid",
        "description": "Show grid for the plot",
        "defaultValue": "True",
        "type": "string"
      },
      {
        "name": "--ci",
        "label": "Show confidence interval [95%]",
        "description": "Show confidence interval for the plot",
        "defaultValue": "True",
        "type": "string"
      },
      {
        "name": "--legend",
        "label": "Show legend",
        "description": "Show legend for the plot",
        "defaultValue": "True",
        "type": "string"
      },
      {
        "name": "--title",
        "label": "Title",
        "description": "Title of the plot",
        "defaultValue": null,
        "type": "string"
      },
      {
        "name": "--x-label",
        "label": "X axis label",
        "description": "Label of the X axis",
        "defaultValue": null,
        "type": "string"
      },
      {
        "name": "--y-label",
        "label": "Y axis label",
        "description": "Label of the Y axis",
        "defaultValue": null,
        "type": "string"
      },
      {
        "name": "--delimiter",
        "label": "Delimiter",
        "description": "Delimiter of the csv file",
        "defaultValue": ",",
        "type": "string"
      },
      {
        "name": "--output-path",
        "readOnly": true,
        "label": "Output path",
        "description": "Path to the output files",
        "defaultValue": "/mnt/shared",
        "type": "string"
      }
    ],
    "inputs": [
      {
        "name": "input",
        "type": "tabulardataset",
        "label": "Input CSV file",
        "path": "/mnt/shared/input.csv"
      }
    ],
    "outputs": [
      {
        "name": "output-pdf",
        "type": "pdf",
        "label": "Output PDF file",
        "path": "/mnt/shared/lineplot.pdf"
      },
      {
        "name": "output-png",
        "type": "image",
        "label": "Output PNG image",
        "path": "/mnt/shared/lineplot.png"
      },
      {
        "name": "output-svg",
        "type": "image",
        "label": "Output SVG image",
        "path": "/mnt/shared/lineplot.svg"
      }
    ],
    "mainScriptPath": "main.py",
    "testPath": "test_main.py",
    "dependencies": [
      {
        "name": "python",
        "version": "3.11.5",
        "license": "PSF",
        "url": "https://www.python.org/"
      }
    ],
    "resources": {
      "cores": 1,
      "memory": 128,
      "gpuNeeded": false,
      "gpuMemory": null,
      "estimatedTimeInMin": 1
    },
    "publicationDate": "2023-11-23T14:30:00.000Z",
    "author": {
      "email": "khaos.research@gmail.com",
      "affiliation": "Khaos Research Group"
    },
    "contributor": [
      {
        "email": "juancaruru@uma.es",
        "affiliation": "Khaos Research Group"
      },
      {
        "email": "dandobjim@uma.es"
      }
    ]
  }

=== KhaosResearch/enbic2lab-images/components/air/AnalyseTrend/annotation.json
{
  "type": "DataSink",
  "name": "analyse-trend",
  "label": "Analyse Trend",
  "description": "Perform Analyse Trend over pollen data",
  "license": "cc by-nc-nd 4.0",
  "version": "1.0.0",
  "dockerImage": "192.168.219.5:8098/enbic2lab/air/analyse_trend:1.0.0",
  "tags": [
    "enbic2lab-air",
    "cc by-nc-nd 4.0", "by-nc-nd",
    "analyse-trend"
  ],
  "parameters": [
    {
      "name": "--filepath",
      "label": "Input Filepath",
      "description": "Input file path",
      "type": "string",
      "defaultValue": "{{.inputs.input.path}}",
      "readOnly": true
    },
    {
      "name": "--interpolation",
      "label": "Apply Interpolation",
      "description": "Apply interpolation to fill gaps in data",
      "type": "string",
      "defaultValue": "true"
    },
    {
      "name": "--intMethod",
      "label": "Interpolation Method",
      "description": "Interpolation method (options: lineal, movingmean, tseries or spline)",
      "type": "string",
      "defaultValue": "lineal"
    },
    {
      "name": "--method",
      "label": "Pollen Season Calculation Method",
      "description": "Method for calculating pollen season (options: percentage, logistic, moving, clinical or grains)",
      "type": "string",
      "defaultValue": "percentage"
    },
    {
      "name": "--quantil",
      "label": "Quantile",
      "description": "Quantile of data to display (between 0 and 1)",
      "type": "number",
      "defaultValue": 0.75
    },
    {
      "name": "--significant",
      "label": "Significance Level",
      "description": "Significance level for linear trends analysis",
      "type": "number",
      "defaultValue": 0.05
    },
    {
      "name": "--split",
      "label": "Split Plot",
      "description": "Split the plot based on variable nature",
      "type": "string",
      "defaultValue": "true"
    },
    {
      "name": "--delimiter",
      "label": "Dataframe Delimiter",
      "description": "Dataframe delimiter",
      "type": "string",
      "defaultValue": ","
    },
    {
      "name": "--output-folder",
      "label": "Output directory",
      "description": "Path to the output directory",
      "defaultValue": "/mnt/shared/",
      "readOnly": true,
      "type": "string"
    }
  ],
  "inputs": [
    {
      "name": "input",
      "label": "Input CSV file",
      "path": "/mnt/shared/input.csv",
      "type": "tabulardataset"
    }
  ],
  "outputs": [
    {
      "name": "output pdf",
      "label": "Output PDF file",
      "path": "/mnt/shared/output.pdf",
      "type": "pdf"
    },
    {
      "name": "output xlsx",
      "label": "Output XLSX file",
      "path": "/mnt/shared/output.xlsx",
      "type": "xlsx"
    }
  ],
  "mainScriptPath": "main.R",
  "testPath": "test_main.R",
  "dependencies": [
    {
      "name": "r",
      "version": "4.3.1",
      "license": "PSF",
      "url": "https://www.r-project.org/"
    }
  ],
  "resources": {
    "cores": 1,
    "memory": 128,
    "gpuNeeded": false,
    "gpuMemory": null,
    "estimatedTimeInMin": 4
  },
  "publicationDate": "2023-11-03T10:00:00.000Z",
  "author": {
    "email": "khaos.research@gmail.com",
    "affiliation": "Khaos Research Group"
  },
  "contributor": [
    {
      "email": "adrianseor.99@uma.es",
      "affiliation": "Khaos Research Group"
    }
  ]
}

=== KhaosResearch/enbic2lab-images/components/flora/PlotDendrogram/annotation.json
{
  "type": "DataAnalysing",
  "name": "plot-dendrogram",
  "label": "Dendrogram",
  "description": "Plot dendrogram from a CSV file",
  "license": "cc by-nc-nd 4.0",
  "version": "1.0.1",
  "dockerImage": "192.168.219.5:8098/enbic2lab/flora/plot_dendrogram:1.0.1",
  "tags": ["enbic2lab-flora", "cc by-nc-nd 4.0", "by-nc-nd", "dendrogram"],
  "parameters": [
    {
      "name": "--filepath",
      "label": "Filepath",
      "description": "Name of the CSV file",
      "defaultValue": "{{.inputs.input.path}}",
      "readOnly": true,
      "type": "string"
    },
    {
      "name": "--delimiter",
      "label": "Delimiter",
      "description": "Delimiter of the CSV file",
      "defaultValue": ";",
      "type": "string"
    },
    {
      "name": "--metrdendrogram",
      "label": "Metric Dendrogram",
      "description": "Distance functions between numeric vectors",
      "defaultValue": "euclidean",
      "type": "string",
      "choices": [
        "braycurtis",
        "canberra",
        "chebyshev",
        "cityblock",
        "correlation",
        "cosine",
        "dice",
        "euclidean",
        "hamming",
        "jaccard",
        "jensenshannon",
        "kulczynski1",
        "mahalanobis",
        "matching",
        "minkowski",
        "rogerstanimoto",
        "russellrao",
        "seuclidean",
        "sokalmichener",
        "sokalsneath",
        "sqeuclidean",
        "yule"
      ]
    },
    {
      "name": "--methdendrogram",
      "label": "Method Dendrogram",
      "description": "Methods for calculating the distance between the newly formed cluster",
      "defaultValue": "ward",
      "type": "string",
      "choices": [
        "single",
        "complete",
        "average",
        "weighted",
        "median",
        "ward",
        "centroid"
      ]
    },
    {
      "name": "--oriendendrogram",
      "label": "Orientation Dendrogram",
      "description": "The orientation of the dendrogram for visualization",
      "defaultValue": "top",
      "type": "string",
      "choices": ["top", "left", "bottom", "right"]
    },
    {
      "name": "--output-path",
      "label": "Output path",
      "description": "Path to the output image",
      "defaultValue": "/mnt/shared",
      "readOnly": true,
      "type": "string"
    }
  ],
  "inputs": [
    {
      "name": "input",
      "label": "Input CSV file",
      "path": "/mnt/shared/input.csv",
      "type": "tabulardataset"
    }
  ],
  "outputs": [
    {
      "name": "output",
      "label": "Output PDF file",
      "path": "/mnt/shared/output.pdf",
      "type": "pdf"
    }
  ],
  "mainScriptPath": "main.py",
  "testPath": "test_main.py",
  "dependencies": [
    {
      "name": "python",
      "version": "3.11.5",
      "license": "PSF",
      "url": "https://www.python.org/"
    }
  ],
  "resources": {
    "cores": 1,
    "memory": 128,
    "gpuNeeded": false,
    "gpuMemory": null,
    "estimatedTimeInMin": 4
  },
  "publicationDate": "2023-09-28T10:00:00.000Z",
  "author": {
    "email": "adrianseor.99@uma.es",
    "affiliation": "Khaos Research Group"
  }
}

=== KhaosResearch/enbic2lab-images/components/air/PollenCalendar/annotation.json
{
  "type": "DataSink",
  "name": "pollen-calendar",
  "label": "Pollen Calendar",
  "description": "Plot pollen callendar for a specific range of years",
  "license": "cc by-nc-nd 4.0",
  "version": "1.0.0",
  "dockerImage": "192.168.219.5:8098/enbic2lab/air/pollen_calendar:1.0.0",
  "tags": [
    "enbic2lab-air",
    "cc by-nc-nd 4.0", "by-nc-nd",
    "plot",
    "calendar"
  ],
  "parameters": [
    {
      "name": "--filepath",
      "label": "Input Filepath",
      "description": "Input file path",
      "type": "string",
      "defaultValue": "{{.inputs.input.path}}",
      "readOnly": true
    },
    {
      "name": "--method",
      "label": "Method",
      "description": "Method to calculate and generate the pollen calendar (options: heatplot, violinplot or phenological, default: heatplot)",
      "type": "string",
      "defaultValue": "heatplot"
    },
    {
      "name": "--nTypes",
      "label": "Number of Types",
      "description": "Number of most abundant pollen types to be represented in the pollen calendar (default: 15)",
      "type": "number",
      "defaultValue": 15
    },
    {
      "name": "--startMonth",
      "label": "Start Month",
      "description": "Month (1-12) when the pollen calendar starts (default: 1)",
      "type": "number",
      "defaultValue": 1
    },
    {
      "name": "--yStart",
      "label": "Start Year",
      "description": "Start year for the pollen calendar (default: NULL)",
      "type": "number",
      "defaultValue": null
    },
    {
      "name": "--yEnd",
      "label": "End Year",
      "description": "End year for the pollen calendar (default: NULL)",
      "type": "number",
      "defaultValue": null
    },
    {
      "name": "--perc1",
      "label": "Percentage 1",
      "description": "Percentage (0-100) for main pollination period (default: 80)",
      "type": "number",
      "defaultValue": 80
    },
    {
      "name": "--perc2",
      "label": "Percentage 2",
      "description": "Percentage (0-100) for early/late pollination period (default: 99)",
      "type": "number",
      "defaultValue": 99
    },
    {
      "name": "--thPollen",
      "label": "Pollen Threshold",
      "description": "Minimum threshold of average pollen concentration (default: 1)",
      "type": "number",
      "defaultValue": 1
    },
    {
      "name": "--averageMethod",
      "label": "Average Method",
      "description": "Moment of the application of the average (options: avg_before or avg_after, default: avg_before)",
      "type": "string",
      "defaultValue": "avg_before"
    },
    {
      "name": "--period",
      "label": "Period",
      "description": "Interval time for the pollen calendar (options: daily or weekly, default: daily)",
      "type": "string",
      "defaultValue": "daily"
    },
    {
      "name": "--methodClasses",
      "label": "Method for Classes",
      "description": "Method to define classes for classifying average pollen concentrations (default: exponential)",
      "type": "string",
      "defaultValue": "exponential"
    },
    {
      "name": "--nClasses",
      "label": "Number of Classes",
      "description": "Number of classes for classifying average pollen concentrations (default: 5)",
      "type": "number",
      "defaultValue": 5
    },
    {
      "name": "--classes",
      "label": "Classes",
      "description": "Thresholds for defining different classes (comma-separated)",
      "type": "string",
      "defaultValue": "25, 50, 100, 300"
    },
    {
      "name": "--color",
      "label": "Color Palette",
      "description": "Color palette for the pollen calendar plot (options: green, red, blue, purple or black, default: green)",
      "type": "string",
      "defaultValue": "green"
    },
    {
      "name": "--interpolation",
      "label": "Interpolation",
      "description": "Apply interpolation to complete gaps in the pollen data (default: TRUE)",
      "type": "string",
      "defaultValue": "true"
    },
    {
      "name": "--intMethod",
      "label": "Interpolation Method",
      "description": "Interpolation method (options: lineal, movingmean, spline or tseries, default: lineal)",
      "type": "string",
      "defaultValue": "lineal"
    },
    {
      "name": "--naRemove",
      "label": "Remove NA Values",
      "description": "Remove NA values for the pollen calendar (default: TRUE)",
      "type": "string",
      "defaultValue": "true"
    },
    {
      "name": "--result",
      "label": "Result Type",
      "description": "Output type for the function (options: plot or table, default: plot)",
      "type": "string",
      "defaultValue": "plot"
    },
    {
      "name": "--legendName",
      "label": "Legend Title",
      "description": "Title of the legend in the plot (default: Pollen / m3)",
      "type": "string",
      "defaultValue": "Pollen / m3"
    },
    {
      "name": "--delimiter",
      "label": "Delimiter",
      "description": "Dataframe delimiter (default: ,)",
      "type": "string",
      "defaultValue": ","
    },
    {
      "name": "--output-folder",
      "label": "Output directory",
      "description": "Path to the output directory",
      "defaultValue": "/mnt/shared/",
      "readOnly": true,
      "type": "string"
    }
  ],
  "inputs": [
    {
      "name": "input",
      "label": "Input CSV file",
      "path": "/mnt/shared/input.csv",
      "type": "tabulardataset"
    }
  ],
  "outputs": [
    {
      "name": "output",
      "label": "Output PDF file",
      "path": "/mnt/shared/output.pdf",
      "type": "pdf"
    }
  ],
  "mainScriptPath": "main.R",
  "testPath": "test_main.R",
  "dependencies": [
    {
      "name": "r",
      "version": "4.3.1",
      "license": "PSF",
      "url": "https://www.r-project.org/"
    }
  ],
  "resources": {
    "cores": 1,
    "memory": 128,
    "gpuNeeded": false,
    "gpuMemory": null,
    "estimatedTimeInMin": 4
  },
  "publicationDate": "2023-11-01T10:00:00.000Z",
  "author": {
    "email": "khaos.research@gmail.com",
    "affiliation": "Khaos Research Group"
  },
  "contributor": [
    {
      "email": "adrianseor.99@uma.es",
      "affiliation": "Khaos Research Group"
    }
  ]
}
