=== KhaosResearch/enbic2lab-images/annotation.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://enbic2lab.uma.es/components.schema.json",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "description": "Specifies the category of the component within the data workflow.",
      "enum": [
        "DataProcessing",
        "DataAnalysing",
        "DataSink",
        "DataCollection",
        "DataFlow"
      ]
    },
    "name": {
      "type": "string",
      "description": "Name of the component with no spaces or special characters."
    },
    "label": {
      "type": "string",
      "description": "A concise, descriptive name for the component that will be displayed in user interfaces."
    },
    "description": {
      "type": "string",
      "description": "A detailed description of the component's purpose and functionality."
    },
    "license": {
      "type": "string",
      "description": "Software license governing the component's use and distribution."
    },
    "version": {
      "type": "string",
      "description": "The release version of the component, following semantic versioning when applicable.",
      "default": "0.0.1"
    },
    "dockerImage": {
      "type": "string",
      "description": "The full identifier for the Docker image used to execute the component, including the repository and tag.",
      "default": "docker.io/docker/hello-world:latest"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "An array of keywords to facilitate search and categorization of the component.",
      "uniqueItems": true
    },
    "parameters": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The unique name used internally by the component to identify the parameter."
          },
          "label": {
            "type": "string",
            "description": "A readable name for the parameter used in user interfaces."
          },
          "description": {
            "type": "string",
            "description": "Explains what the parameter does and how it affects the component's behavior."
          },
          "type": {
            "type": "string",
            "description": "Specifies the expected data type for the parameter value.",
            "enum": [
              "string",
              "number",
              "integer",
              "float",
              "boolean"
            ]
          },
          "defaultValue": {
            "type": [
              "number",
              "string",
              "null"
            ],
            "description": "Provides a default value for the parameter, to be used when no value is explicitly provided.",
            "properties": {}
          },
          "readOnly": {
            "type": "boolean",
            "default": false,
            "description": "Indicates whether this parameter should not be modified by the user. If set to 'true', the parameter is considered read-only and cannot be altered by the user."
          }
        },
        "required": [
          "type",
          "name",
          "label",
          "description"
        ],
        "description": "Parameters that can be configured for the component."
      },
      "uniqueItems": true
    },
    "inputs": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The unique name identifying each input required by the component."
          },
          "label": {
            "type": "string",
            "description": "A label providing a human-readable name for the input."
          },
          "path": {
            "type": "string",
            "description": "The location or source path where the input data can be found."
          },
          "type": {
            "type": "string",
            "description": "The data type of the input.",
            "enum": [
              "bin",
              "fastq",
              "image",
              "map",
              "pdf",
              "rar",
              "sav",
              "shp",
              "tempfile",
              "text",
              "tabulardataset",
              "docx",
              "xlsx",
              "html",
              "json",
              "rdf",
              "xml",
              "tiff",
              "zip",
              "pkl",
              "onnx"
            ]
          }
        },
        "required": [
          "name",
          "label",
          "path",
          "type"
        ],
        "description": "Input data sources for the component."
      }
    },
    "outputs": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The unique name identifying each output generated by the component."
          },
          "label": {
            "type": "string",
            "description": "A label providing a human-readable name for the output."
          },
          "path": {
            "type": "string",
            "description": "The destination path where output data will be written."
          },
          "type": {
            "type": "string",
            "description": "The data type of the output.",
            "enum": [
              "bin",
              "fastq",
              "image",
              "map",
              "pdf",
              "rar",
              "sav",
              "shp",
              "tempfile",
              "text",
              "tabulardataset",
              "docx",
              "xlsx",
              "html",
              "json",
              "rdf",
              "xml",
              "tiff",
              "zip",
              "pkl",
              "onnx"
            ]
          }
        },
        "required": [
          "name",
          "label",
          "path",
          "type"
        ],
        "description": "Output data destinations for the component."
      }
    },
    "mainScriptPath": {
      "type": "string",
      "description": "The filesystem path to the executable script."
    },
    "testPath": {
      "type": "string",
      "description": "The filesystem path to the component's test script or suite."
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of an external library or service that this component relies on-"
          },
          "version": {
            "type": "string",
            "description": "The specified version of the dependency that is known to be compatible with this component."
          },
          "license": {
            "type": "string",
            "description": "The license governing the dependency, which may impact the overall licensing of the component."
          },
          "url": {
            "type": "string",
            "description": "A URL or other locator where the dependency can be accessed or reviewed."
          }
        },
        "required": [
          "name",
          "version",
          "license"
        ],
        "description": "Dependencies required to run the component."
      }
    },
    "resources": {
      "type": "object",
      "properties": {
        "cores": {
          "type": "integer",
          "description": "The number of CPU cores requested for processing."
        },
        "memory": {
          "type": "integer",
          "description": "The quantity of RAM required for the component, specified in Megabytes (MB)."
        },
        "gpuNeeded": {
          "type": "boolean",
          "description": "Flag to indicate whether the component requires GPU support.",
          "default": false
        },
        "gpuMemory": {
          "type": [
            "integer",
            "null"
          ],
          "description": "The amount of GPU memory required, specified in Megabytes (MB), applicable if `gpuNeeded` is true."
        },
        "estimatedTimeInMin": {
          "type": "integer",
          "description": "An approximate time in minutes that the component will take to execute."
        }
      },
      "required": [
        "cores",
        "memory",
        "gpuNeeded",
        "gpuMemory",
        "estimatedTimeInMin"
      ],
      "description": "Resource requirements for running the component."
    },
    "publicationDate": {
      "type": "string",
      "format": "date-time",
      "description": "The date and time when the component was officially made available."
    },
    "author": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "description": "Author email."
        },
        "affiliation": {
          "type": "string",
          "description": "The institution or organization with which the author is associated."
        }
      },
      "required": [
        "email",
        "affiliation"
      ],
      "description": "Identifies the individual or organization responsible for creating the component."
    },
    "contributor": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "format": "email",
            "default": "Contact email.",
            "description": "Contributor email."
          },
          "affiliation": {
            "type": "string",
            "description": "The institution or organization with which the contributor is associated."
          }
        },
        "required": [
          "email"
        ]
      },
      "description": "Contact information for the component's author or contributor."
    },
    "maintainer": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "format": "email",
            "default": "Contact email.",
            "description": "Maintainer email."
          },
          "affiliation": {
            "type": "string",
            "description": "The institution or organization with which the maintainer is associated."
          }
        },
        "required": [
          "email"
        ]
      },
      "description": "Contact information for the component's author or maintainers."
    }
  },
  "required": [
    "type",
    "name",
    "label",
    "description",
    "license",
    "version",
    "dockerImage",
    "outputs",
    "mainScriptPath",
    "dependencies",
    "resources",
    "publicationDate",
    "author"
  ]
}

=== KhaosResearch/enbic2lab-images/components/air/SarimaVisualization/annotation.json
{
  "type": "DataSink",
  "name": "sarimavisualization",
  "label": "Sarima visualization",
  "description": "Given the prediction array, pollen type and the start date for validation, returns the R2 visualisation",
  "license": "cc by-nc-nd 4.0",
  "version": "1.0.0",
  "dockerImage": "192.168.219.5:8098/enbic2lab/air/sarima_visualization:1.0.0",
  "tags": ["enbic2lab-air", "cc by-nc-nd 4.0", "by-nc-nd", "processing"],
  "parameters": [
    {
      "name": "--filepath",
      "label": "File path",
      "description": "Input CSV file path.",
      "defaultValue": "{{.inputs.input.path}}",
      "readOnly": true,
      "type": "string"
    }, 
    {
      "name": "--filepath-prediction",
      "label": "File path prediction",
      "description": "Input CSV file path.",
      "defaultValue": "{{.inputs.input2.path}}",
      "readOnly": true,
      "type": "string"
    },
    {
      "name": "--output",
      "label": "Output file path",
      "description": "Output file path",
      "defaultValue": "/mnt/shared/",
      "readOnly": true,
      "type": "string"
    },
    {
      "name": "--validation-time",
      "label": "Validation time",
      "description": "Validation time",
      "defaultValue": "2020-01-01",
      "type": "string"
    },
    {
      "name": "--date-column",
      "label": "Date column",
      "description": "Name of date column",
      "defaultValue": "fecha",
      "type": "string"
    },
    {
      "name": "--delimiter",
      "label": "Delimiter",
      "description": "Delimiter used in CSV.",
      "defaultValue":";",
      "type": "string"
    }
  ],
  "inputs": [
    {
      "name": "input",
      "label": "Input CSV file",
      "path": "/mnt/shared/Sarima_Y_test.csv",
      "type": "tabulardataset"
    },
    {
      "name": "input2",
      "label": "Input CSV file",
      "path": "/mnt/shared/Sarima_predictions.csv",
      "type": "tabulardataset"
    }
  ],
  "outputs": [
    {
      "name": "output",
      "label": "Output CSV file",
      "path": "/mnt/shared/Sarima_visualisation.png",
      "type": "image"
    }
  ],
  "mainScriptPath": "main.py",
  "testPath": "test_main.py",
  "dependencies": [
    {
      "name": "python",
      "version": "3.11.5",
      "license": "PSF",
      "url": "https://www.python.org/"
    }
  ],
  "resources": {
    "cores": 1,
    "memory": 128,
    "gpuNeeded": false,
    "gpuMemory": null,
    "estimatedTimeInMin": 4
  },
  "publicationDate": "2023-11-17T10:00:00.000Z",
  "author": {
    "email": "juansanchezrodriguez1999@uma.es",
    "affiliation": "Khaos Research Group"
  },
  "contributor": [
    {
      "email": "khaos.research@gmail.com"
    }
  ],
  "maintainer": [
    {
      "email": "khaos.research@gmail.com"
    }
  ]
}

=== KhaosResearch/enbic2lab-images/components/water/ComponentStatisticsETP/annotation.json
{
  "type": "DataAnalysing",
  "name": "etpstatistics",
  "label": "ETP Statistics",
  "description": "Calculates a series of statistic values from the output CSV file of the workflow ",
  "license": "cc by-nc-nd 4.0",
  "version": "1.0.1",
  "dockerImage": "192.168.219.5:8098/enbic2lab/water/etp_statistics_component:1.0.1",
  "tags": [
    "enbic2lab-water",
    "cc by-nc-nd 4.0",
    "by-nc-nd",
    "conversion"
  ],
  "parameters": [
    {
      "name": "--filepath",
      "label": "Filepath",
      "description": "Path to the csv file",
      "defaultValue": "{{.inputs.input.path}}",
      "readOnly": true,
      "type": "string"
    },
    {
      "name": "--output",
      "label": "Output path",
      "description": "Output path of the file",
      "defaultValue": "/mnt/shared/EtpStatistics.csv",
      "type": "string",
      "readOnly": true
    },
    {
      "name": "--delimiter",
      "label": "Delimiter",
      "description": "Delimiter of the csv file",
      "defaultValue": ";",
      "type": "string"
    },
    {
      "name": "--start-year",
      "label": "Start year",
      "defaultValue": 1997,
      "description": "Start year statistics",
      "type": "number"
    },
    {
      "name": "--end-year",
      "label": "End year",
      "defaultValue": 2023,
      "description": "End year statistics",
      "type": "number"
    },
    {
      "name": "--hydrological-year",
      "label": "Hydrological year",
      "description": "Hydrological year (True/False)",
      "defaultValue": "False",
      "type": "string"
    },
    {
      "name": "--variables-list",
      "label": "Variables list",
      "description": "List of variables separated with comma (,) to calculate",
      "defaultValue": "TMAX,TMIN,Latitud,TMedia,Distancia Tierra-Sol",
      "type": "string"
    },
    {
      "name": "--metrics-list",
      "label": "Metrics list",
      "description": "List of metrics separated with comma (,) to calculate",
      "defaultValue": "Max,Min,Mean,Median,Range",
      "type": "string"
    }
  ],
  "inputs": [
    {
      "name": "input",
      "label": "Input CSV file",
      "path": "/mnt/shared/etp_hargreaves_inf.csv",
      "type": "tabulardataset"
    }
  ],
  "outputs": [
    {
      "name": "output",
      "label": "Output CSV file",
      "path": "/mnt/shared/EtpStatistics.csv",
      "type": "tabulardataset"
    }
  ],
  "mainScriptPath": "main.py",
  "testPath": "test_main.py",
  "dependencies": [
    {
      "name": "python",
      "version": "3.11.5",
      "license": "PSF",
      "url": "https://www.python.org/"
    }
  ],
  "resources": {
    "cores": 1,
    "memory": 128,
    "gpuNeeded": false,
    "gpuMemory": null,
    "estimatedTimeInMin": 4
  },
  "publicationDate": "2023-11-15T10:00:00.000Z",
  "author": {
    "email": "juansanchezrodriguez1999@uma.es",
    "affiliation": "Khaos Research Group"
  },
  "contributor": [
    {
      "email": "khaos.research@gmail.com"
    }
  ],
  "maintainer": [
    {
      "email": "khaos.research@gmail.com"
    }
  ]
}

=== KhaosResearch/enbic2lab-images/components/air/PlotTrend/annotation.json
{
  "type": "DataSink",
  "name": "plot-trend",
  "label": "Plot Trend",
  "description": "calculates the main seasonal indexes of the pollen season (Start Date, Peak Date, End Date and Pollen Integral)",
  "license": "cc by-nc-nd 4.0",
  "version": "1.0.0",
  "dockerImage": "192.168.219.5:8098/enbic2lab/air/plot_trend:1.0.0",
  "tags": [
    "enbic2lab-air",
    "cc by-nc-nd 4.0", "by-nc-nd",
    "plot"
  ],
  "parameters": [
    {
      "name": "--filepath",
      "label": "Input Filepath",
      "description": "Input file path",
      "type": "string",
      "defaultValue": "{{.inputs.input.path}}",
      "readOnly": true
    },
    {
      "name": "--interpolation",
      "label": "Apply Interpolation",
      "description": "Apply interpolation to fill gaps",
      "type": "string",
      "defaultValue": "true"
    },
    {
      "name": "--intMethod",
      "label": "Interpolation Method",
      "description": "Interpolation method (lineal, movingmean, spline, tseries)",
      "type": "string",
      "defaultValue": "lineal"
    },
    {
      "name": "--method",
      "label": "Pollen Season Calculation Method",
      "description": "Method for calculating the pollen season",
      "type": "string",
      "defaultValue": "percentage"
    },
    {
      "name": "--delimiter",
      "label": "Dataframe Delimiter",
      "description": "Dataframe delimiter",
      "type": "string",
      "defaultValue": ","
    },
    {
      "name": "--output-folder",
      "label": "Output directory",
      "description": "Path to the output directory",
      "defaultValue": "/mnt/shared/",
      "readOnly": true,
      "type": "string"
    }
  ],
  "inputs": [
    {
      "name": "input",
      "label": "Input CSV file",
      "path": "/mnt/shared/input.csv",
      "type": "tabulardataset"
    }
  ],
  "outputs": [
    {
      "name": "output zip",
      "label": "Output ZIP file",
      "path": "/mnt/shared/output.zip",
      "type": "zip"
    },
    {
      "name": "output xlsx",
      "label": "Output XLSX file",
      "path": "/mnt/shared/output.xlsx",
      "type": "xlsx"
    }
  ],
  "mainScriptPath": "main.R",
  "testPath": "test_main.R",
  "dependencies": [
    {
      "name": "r",
      "version": "4.3.1",
      "license": "PSF",
      "url": "https://www.r-project.org/"
    }
  ],
  "resources": {
    "cores": 1,
    "memory": 128,
    "gpuNeeded": false,
    "gpuMemory": null,
    "estimatedTimeInMin": 4
  },
  "publicationDate": "2023-10-27T10:00:00.000Z",
  "author": {
    "email": "khaos.research@gmail.com",
    "affiliation": "Khaos Research Group"
  },
  "contributor": [
    {
      "email": "adrianseor.99@uma.es",
      "affiliation": "Khaos Research Group"
    }
  ]
}

=== KhaosResearch/enbic2lab-images/components/misc/CountNA/annotation.json
{
    "type": "DataSink",
    "name": "CountNA",
    "label": "CountNA",
    "description": "Percentage calculation of NA in a dataset.",
    "license": "cc by-nc-nd 4.0",
    "version": "1.0.1",
    "dockerImage": "192.168.219.5:8098/enbic2lab/misc/countna:1.0.1",
    "tags": ["enbic2lab-misc", "cc by-nc-nd 4.0", "by-nc-nd", "sink"],
    "parameters": [
      {
        "name": "--filepath",
        "label": "Filepath",
        "description": "Path to the csv file",
        "defaultValue": "{{.inputs.input.path}}",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "--delimiter",
        "label": "Delimiter",
        "description": "Delimiter of the csv file",
        "defaultValue": ";",
        "type": "string"
      },
      {
        "name": "--output-path",
        "label": "Output path",
        "description": "Path to the output file",
        "defaultValue": "/mnt/shared",
        "readOnly": true,
        "type": "string"
      }
    ],
    "inputs": [
      {
        "name": "input",
        "type":"tabulardataset",
        "label": "Input CSV file",
        "path": "/mnt/shared/input.csv"
      }
    ],
    "outputs": [
      {
        "name": "output",
        "type": "pdf",
        "label": "Output PDF file",
        "path": "/mnt/shared/output.pdf"
      }
    ],
    "mainScriptPath": "main.py",
    "testPath": "test_main.py",
    "dependencies": [
      {
        "name": "python",
        "version": "3.11.5",
        "license": "PSF",
        "url": "https://www.python.org/"
      }
    ],
    "resources": {
      "cores": 1,
      "memory": 128,
      "gpuNeeded": false,
      "gpuMemory": null,
      "estimatedTimeInMin": 1
    },
    "publicationDate": "2023-10-31T11:30:00.000Z",
    "author": {
      "email": "khaos.research@gmail.com",
      "affiliation": "Khaos Research Group"
    },
    "contributor": [
      {
        "email": "juancaruru@uma.es",
        "affiliation": "Khaos Research Group"
      }
    ]
  }

=== KhaosResearch/enbic2lab-images/components/air/AemetCreateStationsDataset/annotation.json
{
  "type": "DataProcessing",
  "name": "aemetcreatestationsdataset",
  "label": "Stations Attribute",
  "description": "Create a CSV File with data about an attribute from Aemet for differents stations.",
  "license": "cc by-nc-nd 4.0",
  "version": "1.0.0",
  "dockerImage": "192.168.219.5:8098/enbic2lab/air/create_stations_dataset:1.0.0",
  "tags": [
    "enbic2lab-air",
    "cc by-nc-nd 4.0", "by-nc-nd",
    "stations"
  ],
  "parameters": [
    {
      "name": "--filepath",
      "label": "Filepath",
      "description": "Input path to the JSON file",
      "defaultValue": "{{.inputs.input.path}}",
      "readOnly": true,
      "type": "string"
    },
    {
      "name": "--delimiter",
      "label": "Delimiter",
      "description": "Delimiter of the csv file",
      "defaultValue": ";",
      "type": "string"
    },
    {
      "name": "--output",
      "label": "Output File Name",
      "description": "Output File Name",
      "readOnly": true,
      "defaultValue": "/mnt/shared/output.csv",
      "type": "string"
    },
    {
      "name": "--attribute",
      "label": "Attribute",
      "description": "Attribute to create dataset",
      "defaultValue": "prec",
      "type": "string"
    }
  ],
  "inputs": [
    {
      "name": "input",
      "label": "Input JSON file",
      "path": "/mnt/shared/input.json",
      "type": "json"
    }
  ],
  "outputs": [
    {
      "name": "output",
      "label": "Output CSV file",
      "path": "/mnt/shared/output.csv",
      "type": "tabulardataset"
    }
  ],
  "mainScriptPath": "main.py",
  "testPath": "test_main.py",
  "dependencies": [
    {
      "name": "python",
      "version": "3.11.5",
      "license": "PSF",
      "url": "https://www.python.org/"
    }
  ],
  "resources": {
    "cores": 1,
    "memory": 128,
    "gpuNeeded": false,
    "gpuMemory": null,
    "estimatedTimeInMin": 4
  },
  "publicationDate": "2023-10-06T10:00:00.000Z",
  "author": {
    "email": "khaos.research@gmail.com",
    "affiliation": "Khaos Research Group"
  },
  "contributor": [
    {
      "email": "khaos.research@gmail.com",
      "affiliation": "Khaos Research Group"    }
  ],
  "maintainer": [
    {
      "email": "khaos.research@gmail.com",
      "affiliation": "Khaos Research Group"    }
  ]
}

=== KhaosResearch/enbic2lab-images/components/air/AemetStationWeatherAttributes/annotation.json
{
  "type": "DataCollection",
  "name": "aemetstationweatherattributes",
  "label": "AEMET Stations",
  "description": "Download meteorological data from AEMET for multiple Stations.",
  "license": "cc by-nc-nd 4.0",
  "version": "1.0.0",
  "dockerImage": "192.168.219.5:8098/enbic2lab/air/aemet_station_weather_attributes:1.0.0",
  "tags": [
    "enbic2lab-air",
    "cc by-nc-nd 4.0", "by-nc-nd",
    "attributes"
  ],
  "parameters": [
    {
      "name": "--output",
      "label": "Output File path",
      "description": "Output File path",
      "readOnly": true,
      "defaultValue": "/mnt/shared/output.json",
      "type": "string"
    },
    {
      "name": "--start-date",
      "label": "Start Date",
      "description": "Start date of data",
      "defaultValue": "1991-05-11",
      "type": "string"
    },
    {
      "name": "--end-date",
      "label": "End Date",
      "description": "End date of data",
      "defaultValue": "2021-09-30",
      "type": "string"
    },
    {
      "name": "--analysis-stations",
      "label": "Analysis Stations",
      "description": "Stations to get data",
      "defaultValue": "6155A,6172O,6156X",
      "type": "string"
    },
    {
      "name": "--aemet-api-key",
      "label": "Aemet API key",
      "description": "Api Key providing by AEMET web page (https://opendata.aemet.es/centrodedescargas/altaUsuario?).",
      "type": "string"
    }
  ],
  "inputs": [
  ],
  "outputs": [
    {
      "name": "output",
      "label": "Output JSON file",
      "path": "/mnt/shared/output.json",
      "type": "json"
    }
  ],
  "mainScriptPath": "main.py",
  "testPath": "test_main.py",
  "dependencies": [
    {
      "name": "python",
      "version": "3.11.5",
      "license": "PSF",
      "url": "https://www.python.org/"
    }
  ],
  "resources": {
    "cores": 1,
    "memory": 128,
    "gpuNeeded": false,
    "gpuMemory": null,
    "estimatedTimeInMin": 4
  },
  "publicationDate": "2023-10-06T10:00:00.000Z",
  "author": {
    "email": "khaos.research@gmail.com",
    "affiliation": "Khaos Research Group"
  },
  "contributor": [
    {
      "email": "khaos.research@gmail.com",
      "affiliation": "Khaos Research Group"    }
  ],
  "maintainer": [
    {
      "email": "khaos.research@gmail.com",
      "affiliation": "Khaos Research Group"    }
  ]
}

=== KhaosResearch/enbic2lab-images/components/air/PlotSummary/annotation.json
{
  "type": "DataSink",
  "name": "plot-summary",
  "label": "Plot Summary",
  "description": "Plot pollen data during several seasons",
  "license": "cc by-nc-nd 4.0",
  "version": "1.0.0",
  "dockerImage": "192.168.219.5:8098/enbic2lab/air/plot_summary:1.0.0",
  "tags": [
    "enbic2lab-air",
    "cc by-nc-nd 4.0", "by-nc-nd",
    "summary"
  ],
  "parameters": [
    {
      "name": "--filepath",
      "label": "Input Filepath",
      "description": "Input file path",
      "type": "string",
      "defaultValue": "{{.inputs.input.path}}",
      "readOnly": true
    },
    {
      "name": "--pollen",
      "label": "Particle Name",
      "description": "Particle name (mandatory)",
      "type": "string"
    },
    {
      "name": "--mave",
      "label": "Order of the Moving Average",
      "description": "Order of the moving average (default: 1)",
      "type": "number",
      "defaultValue": 1
    },
    {
      "name": "--normalized",
      "label": "Use Normalized Data",
      "description": "Use normalized data (default: TRUE)",
      "type": "string",
      "defaultValue": "true"
    },
    {
      "name": "--interpolation",
      "label": "Apply Interpolation",
      "description": "Apply interpolation (default: TRUE)",
      "type": "string",
      "defaultValue": "true"
    },
    {
      "name": "--intMethod",
      "label": "Interpolation Method",
      "description": "Interpolation method",
      "type": "string",
      "defaultValue": "lineal"
    },
    {
      "name": "--axisname",
      "label": "Y-axis Title",
      "description": "Y-axis title (default: 'Pollen grains / m3')",
      "type": "string",
      "defaultValue": "Pollen grains / m3"
    },
    {
      "name": "--delimiter",
      "label": "Dataframe Delimiter",
      "description": "Dataframe delimiter",
      "type": "string",
      "defaultValue": ","
    },
    {
      "name": "--output-folder",
      "label": "Output directory",
      "description": "Path to the output directory",
      "defaultValue": "/mnt/shared/",
      "readOnly": true,
      "type": "string"
    }
  ],
  "inputs": [
    {
      "name": "input",
      "label": "Input CSV file",
      "path": "/mnt/shared/input.csv",
      "type": "tabulardataset"
    }
  ],
  "outputs": [
    {
      "name": "output pdf",
      "label": "Output PDF file",
      "path": "/mnt/shared/output.pdf",
      "type": "pdf"
    }
  ],
  "mainScriptPath": "main.R",
  "testPath": "test_main.R",
  "dependencies": [
    {
      "name": "r",
      "version": "4.3.1",
      "license": "PSF",
      "url": "https://www.r-project.org/"
    }
  ],
  "resources": {
    "cores": 1,
    "memory": 128,
    "gpuNeeded": false,
    "gpuMemory": null,
    "estimatedTimeInMin": 4
  },
  "publicationDate": "2023-11-03T10:00:00.000Z",
  "author": {
    "email": "khaos.research@gmail.com",
    "affiliation": "Khaos Research Group"
  },
  "contributor": [
    {
      "email": "adrianseor.99@uma.es",
      "affiliation": "Khaos Research Group"
    }
  ]
}
