=== KhaosResearch/enbic2lab-images/annotation.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://enbic2lab.uma.es/components.schema.json",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "description": "Specifies the category of the component within the data workflow.",
      "enum": [
        "DataProcessing",
        "DataAnalysing",
        "DataSink",
        "DataCollection",
        "DataFlow"
      ]
    },
    "name": {
      "type": "string",
      "description": "Name of the component with no spaces or special characters."
    },
    "label": {
      "type": "string",
      "description": "A concise, descriptive name for the component that will be displayed in user interfaces."
    },
    "description": {
      "type": "string",
      "description": "A detailed description of the component's purpose and functionality."
    },
    "license": {
      "type": "string",
      "description": "Software license governing the component's use and distribution."
    },
    "version": {
      "type": "string",
      "description": "The release version of the component, following semantic versioning when applicable.",
      "default": "0.0.1"
    },
    "dockerImage": {
      "type": "string",
      "description": "The full identifier for the Docker image used to execute the component, including the repository and tag.",
      "default": "docker.io/docker/hello-world:latest"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "An array of keywords to facilitate search and categorization of the component.",
      "uniqueItems": true
    },
    "parameters": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The unique name used internally by the component to identify the parameter."
          },
          "label": {
            "type": "string",
            "description": "A readable name for the parameter used in user interfaces."
          },
          "description": {
            "type": "string",
            "description": "Explains what the parameter does and how it affects the component's behavior."
          },
          "type": {
            "type": "string",
            "description": "Specifies the expected data type for the parameter value.",
            "enum": [
              "string",
              "number",
              "integer",
              "float",
              "boolean"
            ]
          },
          "defaultValue": {
            "type": [
              "number",
              "string",
              "null"
            ],
            "description": "Provides a default value for the parameter, to be used when no value is explicitly provided.",
            "properties": {}
          },
          "readOnly": {
            "type": "boolean",
            "default": false,
            "description": "Indicates whether this parameter should not be modified by the user. If set to 'true', the parameter is considered read-only and cannot be altered by the user."
          }
        },
        "required": [
          "type",
          "name",
          "label",
          "description"
        ],
        "description": "Parameters that can be configured for the component."
      },
      "uniqueItems": true
    },
    "inputs": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The unique name identifying each input required by the component."
          },
          "label": {
            "type": "string",
            "description": "A label providing a human-readable name for the input."
          },
          "path": {
            "type": "string",
            "description": "The location or source path where the input data can be found."
          },
          "type": {
            "type": "string",
            "description": "The data type of the input.",
            "enum": [
              "bin",
              "fastq",
              "image",
              "map",
              "pdf",
              "rar",
              "sav",
              "shp",
              "tempfile",
              "text",
              "tabulardataset",
              "docx",
              "xlsx",
              "html",
              "json",
              "rdf",
              "xml",
              "tiff",
              "zip",
              "pkl",
              "onnx"
            ]
          }
        },
        "required": [
          "name",
          "label",
          "path",
          "type"
        ],
        "description": "Input data sources for the component."
      }
    },
    "outputs": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The unique name identifying each output generated by the component."
          },
          "label": {
            "type": "string",
            "description": "A label providing a human-readable name for the output."
          },
          "path": {
            "type": "string",
            "description": "The destination path where output data will be written."
          },
          "type": {
            "type": "string",
            "description": "The data type of the output.",
            "enum": [
              "bin",
              "fastq",
              "image",
              "map",
              "pdf",
              "rar",
              "sav",
              "shp",
              "tempfile",
              "text",
              "tabulardataset",
              "docx",
              "xlsx",
              "html",
              "json",
              "rdf",
              "xml",
              "tiff",
              "zip",
              "pkl",
              "onnx"
            ]
          }
        },
        "required": [
          "name",
          "label",
          "path",
          "type"
        ],
        "description": "Output data destinations for the component."
      }
    },
    "mainScriptPath": {
      "type": "string",
      "description": "The filesystem path to the executable script."
    },
    "testPath": {
      "type": "string",
      "description": "The filesystem path to the component's test script or suite."
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of an external library or service that this component relies on-"
          },
          "version": {
            "type": "string",
            "description": "The specified version of the dependency that is known to be compatible with this component."
          },
          "license": {
            "type": "string",
            "description": "The license governing the dependency, which may impact the overall licensing of the component."
          },
          "url": {
            "type": "string",
            "description": "A URL or other locator where the dependency can be accessed or reviewed."
          }
        },
        "required": [
          "name",
          "version",
          "license"
        ],
        "description": "Dependencies required to run the component."
      }
    },
    "resources": {
      "type": "object",
      "properties": {
        "cores": {
          "type": "integer",
          "description": "The number of CPU cores requested for processing."
        },
        "memory": {
          "type": "integer",
          "description": "The quantity of RAM required for the component, specified in Megabytes (MB)."
        },
        "gpuNeeded": {
          "type": "boolean",
          "description": "Flag to indicate whether the component requires GPU support.",
          "default": false
        },
        "gpuMemory": {
          "type": [
            "integer",
            "null"
          ],
          "description": "The amount of GPU memory required, specified in Megabytes (MB), applicable if `gpuNeeded` is true."
        },
        "estimatedTimeInMin": {
          "type": "integer",
          "description": "An approximate time in minutes that the component will take to execute."
        }
      },
      "required": [
        "cores",
        "memory",
        "gpuNeeded",
        "gpuMemory",
        "estimatedTimeInMin"
      ],
      "description": "Resource requirements for running the component."
    },
    "publicationDate": {
      "type": "string",
      "format": "date-time",
      "description": "The date and time when the component was officially made available."
    },
    "author": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "description": "Author email."
        },
        "affiliation": {
          "type": "string",
          "description": "The institution or organization with which the author is associated."
        }
      },
      "required": [
        "email",
        "affiliation"
      ],
      "description": "Identifies the individual or organization responsible for creating the component."
    },
    "contributor": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "format": "email",
            "default": "Contact email.",
            "description": "Contributor email."
          },
          "affiliation": {
            "type": "string",
            "description": "The institution or organization with which the contributor is associated."
          }
        },
        "required": [
          "email"
        ]
      },
      "description": "Contact information for the component's author or contributor."
    },
    "maintainer": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "format": "email",
            "default": "Contact email.",
            "description": "Maintainer email."
          },
          "affiliation": {
            "type": "string",
            "description": "The institution or organization with which the maintainer is associated."
          }
        },
        "required": [
          "email"
        ]
      },
      "description": "Contact information for the component's author or maintainers."
    }
  },
  "required": [
    "type",
    "name",
    "label",
    "description",
    "license",
    "version",
    "dockerImage",
    "outputs",
    "mainScriptPath",
    "dependencies",
    "resources",
    "publicationDate",
    "author"
  ]
}

=== KhaosResearch/enbic2lab-images/components/flora/SpeciesStatistics/annotation.json
{
  "type": "DataAnalysing",
  "name": "species-statistics",
  "label": "Species Statistics",
  "description": "Calculation of presence and coverage mean of plant species",
  "license": "cc by-nc-nd 4.0",
  "version": "1.0.1",
  "dockerImage": "192.168.219.5:8098/enbic2lab/flora/species_statistics:1.0.1",
  "tags": ["enbic2lab-flora", "cc by-nc-nd 4.0", "by-nc-nd", "analysis"],
  "parameters": [
    {
      "name": "--filepath",
      "label": "File path",
      "description": "Filepath for the input CSV File",
      "defaultValue": "{{.inputs.input.path}}",
      "readOnly": true,
      "type": "string"
    },
    {
      "name": "--delimiter",
      "label": "Delimiter",
      "description": "Delimiter of the classes in the input CSV File",
      "defaultValue": ";",
      "type": "string"
    },
    {
      "name": "--output-path",
      "label": "Output path",
      "description": "Path to the output image",
      "defaultValue": "/mnt/shared",
      "readOnly": true,
      "type": "string"
    }
  ],
  "inputs": [
    {
      "name": "input",
      "label": "Input CSV file",
      "path": "/mnt/shared/inventory_transformation.csv",
      "type": "tabulardataset"
    }
  ],
  "outputs": [
    {
      "name": "output",
      "label": "Output CSV file",
      "path": "/mnt/shared/species_statistics.csv",
      "type": "tabulardataset"
    }
  ],
  "mainScriptPath": "main.py",
  "testPath": "test_main.py",
  "dependencies": [
    {
      "name": "python",
      "version": "3.11.5",
      "license": "PSF",
      "url": "https://www.python.org/"
    }
  ],
  "resources": {
    "cores": 1,
    "memory": 128,
    "gpuNeeded": false,
    "gpuMemory": null,
    "estimatedTimeInMin": 4
  },
  "publicationDate": "2023-09-26T10:00:00.000Z",
  "author": {
    "email": "juansanchezrodriguez1999@uma.es",
    "affiliation": "Khaos Research Group"
  }
}

=== KhaosResearch/enbic2lab-images/components/water/PlotTemperature/annotation.json
{
  "type": "DataAnalysing",
  "name": "temperatureplot",
  "label": "Temperature Plot",
  "description": "From the input CSV file, this component is responsible for plotting the maximum and minimum temperature per day on a graph.",
  "license": "cc by-nc-nd 4.0",
  "version": "1.0.0",
  "dockerImage": "192.168.219.5:8098/enbic2lab/water/temperature_plot_component:1.0.0",
  "tags": [
    "enbic2lab-water",
    "cc by-nc-nd 4.0", "by-nc-nd",
    "conversion"
  ],
  "parameters": [
    {
      "name": "--filepath",
      "label": "Filepath",
      "description": "Path to the csv file",
      "defaultValue": "{{.inputs.input.path}}",
      "readOnly": true,
      "type": "string"
    },
    {
      "name": "--delimiter",
      "label": "Delimiter",
      "description": "Delimiter of the csv file",
      "defaultValue": ";",
      "type": "string"
    },
    {
      "name": "--mode",
      "label": "Mode",
      "description": "Plot mode",
      "defaultValue": "both",
      "type": "string"
    },
    {
      "name": "--output",
      "label": "Output",
      "description": "Path to the html file",
      "defaultValue": "/mnt/shared/Temperature_plot.html",
      "readOnly": true,
      "type": "string"
    }
  ],
  "inputs": [
    {
      "name": "input",
      "label": "Input CSV file",
      "path": "/mnt/shared/ComponentINF.csv",
      "type": "tabulardataset"
    }
  ],
  "outputs": [
    {
      "name": "output",
      "label": "Output HTML file",
      "path": "/mnt/shared/Temperature_plot.html",
      "type": "html"
    }
  ],
  "mainScriptPath": "main.py",
  "testPath": "test_main.py",
  "dependencies": [
    {
      "name": "python",
      "version": "3.11.5",
      "license": "PSF",
      "url": "https://www.python.org/"
    }
  ],
  "resources": {
    "cores": 1,
    "memory": 128,
    "gpuNeeded": false,
    "gpuMemory": null,
    "estimatedTimeInMin": 4
  },
  "publicationDate": "2023-11-09T10:00:00.000Z",
  "author": {
    "email": "juansanchezrodriguez1999@uma.es",
    "affiliation": "Khaos Research Group"
  },
  "contributor": [
    {
      "email": "khaos.research@gmail.com"
    }
  ],
  "maintainer": [
    {
      "email": "khaos.research@gmail.com"
    }
  ]
}

=== KhaosResearch/enbic2lab-images/components/misc/RelationPlot/annotation.json
{
    "type": "DataSink",
    "name": "GenericRelplot",
    "label": "Relation Plot",
    "description": "Generic simple Relation plot",
    "license": "cc by-nc-nd 4.0",
    "version": "1.0.0",
    "dockerImage": "192.168.219.5:8098/enbic2lab/misc/generic_relplot:1.0.0",
    "tags": ["enbic2lab-misc", "cc by-nc-nd 4.0", "by-nc-nd", "Sink", "generic"],
    "parameters": [
      {
        "name": "--filepath",
        "label": "Filepath",
        "description": "Path to the CSV file",
        "defaultValue": "{{.inputs.input.path}}",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "--x-column",
        "label": "Column for X axis",
        "description": "Column name for the X axis",
        "type": "string"
      },
      {
        "name": "--y-column",
        "label": "Column for Y axis",
        "description": "Column name for the Y axis",
        "type": "string"
      },
      {
        "name": "--kind",
        "label": "Kind of plot",
        "description": "Kind of plot to generate",
        "defaultValue": "scatter",
        "type": "string",
        "choices": ["scatter", "line"]
      },
      {
        "name": "--palette",
        "label": "Palette",
        "description": "Color palette to use",
        "defaultValue": "tab10",
        "type": "string"
      },
      {
        "name": "--hue",
        "label": "Hue column",
        "description": "Column name for the hue",
        "defaultValue": null,
        "type": "string"
      },
      {
        "name": "--size",
        "label": "Size column",
        "description": "Column name for the size",
        "defaultValue": null,
        "type": "string"
      },
      {
        "name": "--style",
        "label": "Style column",
        "description": "Column name for the style",
        "defaultValue": null,
        "type": "string"
      },
      {
        "name": "--col",
        "label": "Subplot in columns column",
        "description": "Column name for the subplot in columns",
        "defaultValue": null,
        "type": "string"
      },
      {
        "name": "--row",
        "label": "Subplot in rows column",
        "description": "Column name for the subplot in rows",
        "defaultValue": null,
        "type": "string"
      },
      {
        "name": "--delimiter",
        "label": "Delimiter",
        "description": "Delimiter of the csv file",
        "defaultValue": ",",
        "type": "string"
      },
      {
        "name": "--output-path",
        "readOnly": true,
        "label": "Output path",
        "description": "Path to the output files",
        "defaultValue": "/mnt/shared",
        "type": "string"
      }
    ],
    "inputs": [
      {
        "name": "input",
        "type": "tabulardataset",
        "label": "Input CSV file",
        "path": "/mnt/shared/input.csv"
      }
    ],
    "outputs": [
      {
        "name": "output-pdf",
        "type": "pdf",
        "label": "Output PDF file",
        "path": "/mnt/shared/relplot.pdf"
      },
      {
        "name": "output-png",
        "type": "image",
        "label": "Output PNG image",
        "path": "/mnt/shared/relplot.png"
      },
      {
        "name": "output-svg",
        "type": "image",
        "label": "Output SVG image",
        "path": "/mnt/shared/relplot.svg"
      }
    ],
    "mainScriptPath": "main.py",
    "testPath": "test_main.py",
    "dependencies": [
      {
        "name": "python",
        "version": "3.11.5",
        "license": "PSF",
        "url": "https://www.python.org/"
      }
    ],
    "resources": {
      "cores": 1,
      "memory": 128,
      "gpuNeeded": false,
      "gpuMemory": null,
      "estimatedTimeInMin": 1
    },
    "publicationDate": "2023-11-23T14:30:00.000Z",
    "author": {
      "email": "khaos.research@gmail.com",
      "affiliation": "Khaos Research Group"
    },
    "contributor": [
      {
        "email": "juancaruru@uma.es",
        "affiliation": "Khaos Research Group"
      },
      {
        "email": "dandobjim@uma.es"
      }
    ]
  }

=== KhaosResearch/enbic2lab-images/components/flora/SumSpeciesStatisticsPlot/annotation.json
{
  "type": "DataAnalysing",
  "name": "sum-species-statistics-plot",
  "label": "Species Statistics Plot",
  "description": "Plot the top n species of the input CSV File.",
  "license": "cc by-nc-nd 4.0",
  "version": "1.0.1",
  "dockerImage": "192.168.219.5:8098/enbic2lab/flora/sum_species_statistics_plot:1.0.1",
  "tags": ["enbic2lab-flora", "cc by-nc-nd 4.0", "by-nc-nd", "statistics"],
  "parameters": [
    {
      "name": "--filepath",
      "label": "Filepath",
      "description": "Filepath of the CSV file",
      "defaultValue": "{{.inputs.input.path}}",
      "readOnly": true,
      "type": "string"
    },
    {
      "name": "--delimiter",
      "label": "Delimiter",
      "description": "Delimiter of the CSV file",
      "defaultValue": ";",
      "type": "string"
    },
    {
      "name": "--n-samples",
      "label": "Number of Samples",
      "description": "Number of samples that will appear in the plot",
      "type": "integer"
    },
    {
      "name": "--color-plot",
      "label": "Color Plot",
      "description": "Hexadecimal code for color plot",
      "defaultValue": "#006400",
      "type": "string"
    },
    {
      "name": "--output-path",
      "label": "Output path",
      "description": "Path to the output image",
      "defaultValue": "/mnt/shared",
      "readOnly": true,
      "type": "string"
    }
  ],
  "inputs": [
    {
      "name": "input",
      "label": "Input CSV file",
      "path": "/mnt/shared/input.csv",
      "type": "tabulardataset"
    }
  ],
  "outputs": [
    {
      "name": "output",
      "label": "Output PDF file",
      "path": "/mnt/shared/output.pdf",
      "type": "pdf"
    }
  ],
  "mainScriptPath": "main.py",
  "testPath": "test_main.py",
  "dependencies": [
    {
      "name": "python",
      "version": "3.11.5",
      "license": "PSF",
      "url": "https://www.python.org/"
    }
  ],
  "resources": {
    "cores": 1,
    "memory": 128,
    "gpuNeeded": false,
    "gpuMemory": null,
    "estimatedTimeInMin": 4
  },
  "publicationDate": "2023-09-28T10:00:00.000Z",
  "author": {
    "email": "adrianseor.99@uma.es",
    "affiliation": "Khaos Research Group"
  }
}

=== KhaosResearch/enbic2lab-images/components/water/SeriesCompletion/annotation.json
{
    "type": "DataAnalysing",
    "name": "ComponentSeriesCompletion",
    "label": "Series Completion",
    "description": "Complete the data series using several tests and criteria",
    "license": "cc by-nc-nd 4.0",
    "version": "1.0.5",
    "dockerImage": "192.168.219.5:8098/enbic2lab/water/series_completion:1.0.5",
    "tags": ["enbic2lab-water", "cc by-nc-nd 4.0", "by-nc-nd", "Analysing", "precipitation"],
    "parameters": [
      {
        "name": "--filepath",
        "label": "Filepath",
        "description": "Filepath for the input CSV File",
        "defaultValue": "{{.inputs.input.path}}",
        "readOnly": true,
        "type": "string"
      },
      {
        "name": "--start-date",
        "label": "Start date",
        "description": "Start date of the time series",
        "defaultValue": "1993-01-01",
        "type": "string"
      },
      {
        "name": "--end-date",
        "label": "End date",
        "description": "End date of the time series",
        "defaultValue": "2018-12-31",
        "type": "string"
      },
      {
        "name": "--target-station",
        "label": "Target Station",
        "description": "Target station to complete",
        "required": true,
        "type": "string"
      },
      {
        "name": "--analysis-stations",
        "label": "Stations to analyze",
        "description": "Comma (',') separated list of stations to use for the analysis",
        "required": true,
        "type": "string"
      },
      {
        "name": "--completion-criteria",
        "label": "Completion Criteria",
        "description": "List of criteria that will be used to complete the target station. Values that can be included in the list (comma separated) are `r2`, `slope` and `pair`. By default, every criteria will be used.",
        "defaultValue": "r2, slope, pair",
        "type": "string"
      },
      {
        "name": "--tests",
        "label": "Homogeneity tests",
        "description": "Homogeneity tests to perform. Values that can be included in the list (comma separated) are `pettit`, `snht` and `buishand`. By default, every test will be performed.",
        "defaultValue": "pettit, snht, buishand",
        "type": "string"
      },
      {
        "name": "--delimiter",
        "label": "Delimiter",
        "description": "Delimiter of the csv file",
        "defaultValue": ";",
        "type": "string"
      },
      {
        "name": "--output-path",
        "readOnly": true,
        "label": "Output path",
        "description": "Path for the output files",
        "defaultValue": "/mnt/shared",
        "type": "string"
      }
    ],
    "inputs": [
      {
        "name": "input",
        "type": "tabulardataset",
        "label": "Input TimeSeries CSV file",
        "path": "/mnt/shared/PrecipitationTimeSeries.csv"
      }
    ],
    "outputs": [
      {
        "name": "output_completed_data",
        "type": "tabulardataset",
        "label": "Output CSV file of the completed data",
        "path": "/mnt/shared/CompletedData.csv"
      },
      {
        "name": "StationsAnalysis",
        "type": "tabulardataset",
        "label": "Output CSV file of the stations analysis",
        "path": "/mnt/shared/StationsAnalysis.csv"
      },
      {
        "name": "TargetCompleted",
        "type": "tabulardataset",
        "label": "Output CSV file of the target completion",
        "path": "/mnt/shared/TargetCompleted.csv"
      },
      {
        "name": "HomogeneityTests",
        "type": "tabulardataset",
        "label": "Output CSV file of the homogeneity tests realized",
        "path": "/mnt/shared/HomogeneityTests.csv"
      }
    ],
    "mainScriptPath": "main.py",
    "testPath": "test_main.py",
    "dependencies": [
      {
        "name": "python",
        "version": "3.11.5",
        "license": "PSF",
        "url": "https://www.python.org/"
      }
    ],
    "resources": {
      "cores": 1,
      "memory": 128,
      "gpuNeeded": false,
      "gpuMemory": null,
      "estimatedTimeInMin": 20
    },
    "publicationDate": "2023-10-31T11:30:00.000Z",
    "author": {
      "email": "khaos.research@gmail.com",
      "affiliation": "Khaos Research Group"
    },
    "contributor": [
      {
        "email": "juancaruru@uma.es",
        "affiliation": "Khaos Research Group"
      },
      {
        "email": "iresanjim@uma.es",
        "affiliation":"Khaos Research Group"
      }
    ]
  }

=== KhaosResearch/enbic2lab-images/components/flora/JSON2DB/annotation.json
{
    "type": "DataSink",
    "name": "json2db",
    "label": "JSON2DB",
    "description": "Upload the json provided as input to a database",
    "license": "cc by-nc-nd 4.0",
    "version": "1.0.0",
    "dockerImage": "192.168.219.5:8098/enbic2lab/flora/json2db:1.0.0",
    "tags": [
        "enbic2lab",
        "flora",
        "samples",
        "taxons"
    ],
    "parameters": [
        {
            "name": "--filepath",
            "label": "Input JSON file",
            "description": "Input JSON file",
            "defaultValue": "{{.inputs.input.path}}",
            "readOnly": true,
            "type": "string"
        },
        {
            "name": "--collection-name",
            "label": "Collection name",
            "description": "Name of the collection in the database to which documents are to be uploaded. Options: floras_samples, floras_taxones",
            "type": "string",
            "choices": [
                "floras_samples",
                "floras_taxones"
            ]
        },
        {
            "name": "--collision-policy",
            "label": "Collision policy",
            "description": "Strategy to be used in case of database collision. Options: replace, ignore",
            "type": "string",
            "choices": [
                "replace",
                "ignore"
            ]
        }
    ],
    "inputs": [
        {
            "name": "input",
            "label": "Input JSON file",
            "path": "/mnt/shared/input.json",
            "type": "json"
        }
    ],
    "outputs": [],
    "mainScriptPath": "main.py",
    "testPath": "test_main.py",
    "dependencies": [
        {
            "name": "python",
            "version": "3.11.5",
            "license": "PSF",
            "url": "https://www.python.org/"
        }
    ],
    "resources": {
        "cores": 1,
        "memory": 128,
        "gpuNeeded": false,
        "gpuMemory": null,
        "estimatedTimeInMin": 4
    },
    "publicationDate": "2023-12-14T10:00:00.000Z",
    "author": {
        "email": "khaos.research@gmail.com",
        "affiliation": "Khaos Research Group"
    },
    "contributor": [
        {
            "email": "khaos.research@gmail.com",
            "affiliation": "Khaos Research Group"
        }
    ],
    "maintainer": [
        {
            "email": "khaos.research@gmail.com",
            "affiliation": "Khaos Research Group"
        }
    ]
}
